import { z } from "zod";

export const personelSchema = z.object({
  // Personel Bilgileri
  SicilNo: z.string(),
  TcKimlikNo: z.string(),
  Ad: z.string().min(1, "Ad zorunludur."),
  Soyad: z.string().min(1, "Soyad zorunludur."),
  IlkSoyad: z.string(),
  Cinsiyet: z.string(),
  DogumTarihi: z.string(),
  DogumYeri: z.string(),
  MedeniDurum: z.string(),
  Uyruk: z.string(),
  KanGurubu: z.string(),
  OgrenimDurumu: z.string(),
  MezuniyetYili: z.string(),
  MezuniyetBolumu: z.string(),
  Boy: z.string(),
  Kilo: z.string(),
  Yas: z.string(),
  KimlikKartiSeriNo: z.string(),
  KimlikKartiDuzenlemeTarihi: z.string(),
  KimlikKartiBitisTarihi: z.string(),
  OzurluDurumu: z.boolean(),
  OzurlulukDerecesi: z.string(),
  Aciklama: z.string(),

  // Giriş/Çıkış Bilgileri
  IseIlkGirisTarihi: z.string(),
  IseSonGirisTarihi: z.string(),
  CikisTarihi: z.string(),
  Durum: z.boolean(),
  SgkDurumu: z.string(),
  IstihdamDurumu: z.string(),
  CalismaDurumu: z.string(),
  PersonelAyrilisKodu: z.string(),
  IDPersonelIstisnaDurum: z.string(),
  IstisnaDurumBilgi: z.string(),
  IstisnaDurumTarih: z.string(),
  IskurKayit: z.boolean(),
  IskurKayitNo: z.string(),
  AzCalismaDurumu: z.boolean(),
  AzCalismaDurumuGun: z.boolean(),
  AzCalismaDurumuGunSayisi: z.string(),
  EskiHukumluDurumu: z.boolean(),
  SendikaDurumu: z.boolean(),
  SendikaBaslangicTarihi: z.string(),
  DayanismaDurumu: z.boolean(),
  DayanismaBaslangicTarihi: z.string(),
  GecmistenKalanIzinGun: z.string(),

  // Bordro Bilgileri
  Ucret: z.string(),
  MaasParaBirimi: z.string(),
  OdemeSekli: z.string(),
  UcretTipi: z.string(),
  GunlukUcret: z.string(),
  SaatlikUcret: z.string(),
  SozlesmeUcret: z.string(),
  SozlesmeOdemeSekli: z.string(),
  SozlesmeUcret2: z.string(),
  SozlesmeOdemeSekli2: z.string(),
  Ucret2: z.string(),
  GunlukUcret2: z.string(),
  SaatlikUcret2: z.string(),
  NetUcret: z.string(),
  AgiAlmazDurumu: z.boolean(),
  AgiOrani: z.string(),
  AgiOranID: z.string(),
  BesKesilmezDurumu: z.boolean(),
  BesOrani: z.string(),
  DevredenSgkMatrahi: z.string(),
  KumulatifSgkMatrahi: z.string(),
  AuKumulatifVergiMatrahi: z.string(),
  TesvikOrani: z.string(),
  VergidenMuaf: z.boolean(),
  YardimHaric: z.boolean(),
  AgiHaric: z.boolean(),
  MaliMesuliyet: z.boolean(),
  CocukYardimiAlamaz: z.boolean(),
  BordroIstisnaUygulama: z.boolean(),
  UcretOtomatikIsle: z.boolean(),
  UcretOdemeGun: z.string(),
  HastalikRiskPrimDurumu: z.boolean(),
  AsgeriUcretli: z.boolean(),
  IDBanka: z.string(),
  BankaSubeKodu: z.string(),
  BankaHesapNo: z.string(),
  BankaIbanNo: z.string(),
  PersonelMeslekKodu: z.string(),
  PersonelSgkBelgeTuru: z.string(),
  PersonelKanunNo: z.string(),
  PersonelGorevKodu: z.string(),
  PersonelSigortaKolu: z.string(),
  GorevAdi: z.string(),
  UnvanAdi: z.string(),
  OzelKod: z.string(),
  OzelKod2: z.string(),

  // Adres Bilgileri
  Adres: z.string(),
  Telefon: z.string(),
  IlKodu: z.string(),
  IlceKodu: z.string(),
  IDLokasyon: z.string(),
  Koordinatorluk: z.string(),
  CalismaAlani: z.string(),
});

export type PersonelForm = z.infer<typeof personelSchema>;

export const DEFAULT_PERSONEL_FORM: PersonelForm = {
  SicilNo: "",
  TcKimlikNo: "",
  Ad: "",
  Soyad: "",
  IlkSoyad: "",
  Cinsiyet: "",
  DogumTarihi: "",
  DogumYeri: "",
  MedeniDurum: "",
  Uyruk: "",
  KanGurubu: "",
  OgrenimDurumu: "",
  MezuniyetYili: "",
  MezuniyetBolumu: "",
  Boy: "",
  Kilo: "",
  Yas: "",
  KimlikKartiSeriNo: "",
  KimlikKartiDuzenlemeTarihi: "",
  KimlikKartiBitisTarihi: "",
  OzurluDurumu: false,
  OzurlulukDerecesi: "",
  Aciklama: "",

  IseIlkGirisTarihi: "",
  IseSonGirisTarihi: "",
  CikisTarihi: "",
  Durum: true,
  SgkDurumu: "",
  IstihdamDurumu: "",
  CalismaDurumu: "",
  PersonelAyrilisKodu: "",
  IDPersonelIstisnaDurum: "",
  IstisnaDurumBilgi: "",
  IstisnaDurumTarih: "",
  IskurKayit: false,
  IskurKayitNo: "",
  AzCalismaDurumu: false,
  AzCalismaDurumuGun: false,
  AzCalismaDurumuGunSayisi: "",
  EskiHukumluDurumu: false,
  SendikaDurumu: false,
  SendikaBaslangicTarihi: "",
  DayanismaDurumu: false,
  DayanismaBaslangicTarihi: "",
  GecmistenKalanIzinGun: "",

  Ucret: "",
  MaasParaBirimi: "",
  OdemeSekli: "",
  UcretTipi: "",
  GunlukUcret: "",
  SaatlikUcret: "",
  SozlesmeUcret: "",
  SozlesmeOdemeSekli: "",
  SozlesmeUcret2: "",
  SozlesmeOdemeSekli2: "",
  Ucret2: "",
  GunlukUcret2: "",
  SaatlikUcret2: "",
  NetUcret: "",
  AgiAlmazDurumu: false,
  AgiOrani: "",
  AgiOranID: "",
  BesKesilmezDurumu: false,
  BesOrani: "",
  DevredenSgkMatrahi: "",
  KumulatifSgkMatrahi: "",
  AuKumulatifVergiMatrahi: "",
  TesvikOrani: "",
  VergidenMuaf: false,
  YardimHaric: false,
  AgiHaric: false,
  MaliMesuliyet: false,
  CocukYardimiAlamaz: false,
  BordroIstisnaUygulama: false,
  UcretOtomatikIsle: false,
  UcretOdemeGun: "",
  HastalikRiskPrimDurumu: false,
  AsgeriUcretli: false,
  IDBanka: "",
  BankaSubeKodu: "",
  BankaHesapNo: "",
  BankaIbanNo: "",
  PersonelMeslekKodu: "",
  PersonelSgkBelgeTuru: "",
  PersonelKanunNo: "",
  PersonelGorevKodu: "",
  PersonelSigortaKolu: "",
  GorevAdi: "",
  UnvanAdi: "",
  OzelKod: "",
  OzelKod2: "",

  Adres: "",
  Telefon: "",
  IlKodu: "",
  IlceKodu: "",
  IDLokasyon: "",
  Koordinatorluk: "",
  CalismaAlani: "",
};
